version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # Porta de mensagens
      - "15672:15672"   # Porta da interface web de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker-insert:
    build:
      context: .
      dockerfile: Queue.Insert/Dockerfile
    image: worker-insert
    restart: always
    depends_on:
      - rabbitmq

  worker-update:
    build:
      context: .
      dockerfile: Queue.Update/Dockerfile
    image: worker-update
    restart: always
    depends_on:
      - rabbitmq

  worker-delete:
    build:
      context: .
      dockerfile: Queue.Delete/Dockerfile
    image: worker-delete
    restart: always
    depends_on:
      - rabbitmq