version: "3.9"
services:
  worker-insert:
    build:
      context: .
      dockerfile: Queue.Insert/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    image: worker-insert
    restart: always
    networks:
      - external-network

  worker-update:
    build:
      context: .
      dockerfile: Queue.Update/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    image: worker-update
    restart: always
    networks:
      - external-network

  worker-delete:
    build:
      context: .
      dockerfile: Queue.Delete/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    image: worker-delete
    restart: always
    networks:
      - external-network

networks:
  external-network:
    external: true
